"""Transparent operation-count energy model for the retention-vs-cost axis.

We do NOT claim measured joules (that needs the silicon; see bss2.py and K2). We
count operations and multiply by clearly-labelled per-operation energy constants,
and report RELATIVE cost. The load-bearing point is qualitative and robust to the
constants: on a von-Neumann accelerator (GPU) the diffusion noise must be
GENERATED (an RNG draw + a scaled add per weight per step) and the barrier drift
COMPUTED; on analog neuromorphic silicon the same stochastic term is the device's
own intrinsic noise -- physically free. So a GPU PAYS, per consolidation step, an
energy tax that the chip does not. The model makes that tax explicit.

Constants are order-of-magnitude figures from the literature, marked as such; the
paper reports the RATIO (GPU-with-noise vs noise-free / silicon), which is
insensitive to their absolute value.
"""
from __future__ import annotations

from dataclasses import dataclass

# --- per-operation energy, 45nm-ish CMOS order-of-magnitude (Horowitz 2014) --- #
# labelled approximate; only ratios are reported.
E_MAC_PJ = 3.1          # 32b float multiply-add, ~pJ
E_ADD_PJ = 0.9          # 32b float add
E_RNG_PJ = 7.0          # one pseudo-random Gaussian draw (several flops + transcendental)
E_TANH_PJ = 5.0         # one transcendental (tan for the Doob score)
# BrainScaleS-2: analog MAC energy per synaptic operation, ~fJ-scale (Pehle 2022,
# accelerated analog); intrinsic noise is generated by device physics -> 0 extra.
E_MAC_BSS2_PJ = 0.01    # labelled order-of-magnitude for an analog synaptic op


@dataclass
class StepCost:
    macs: int = 0            # multiply-accumulates (forward+backward)
    adds: int = 0            # extra vector adds (drift, noise add)
    rng: int = 0            # gaussian draws (noise)
    tanh: int = 0            # transcendental evals (Doob score)

    def energy_pj(self, mac_pj=E_MAC_PJ):
        return (self.macs * mac_pj + self.adds * E_ADD_PJ
                + self.rng * E_RNG_PJ + self.tanh * E_TANH_PJ)


def forward_backward_macs(n_params):
    """~2 MACs/param forward, ~4 MACs/param backward for an MLP (grad wrt weights
    and inputs). Order-of-magnitude; identical across methods so it cancels in the
    method-vs-method ratio but sets the noise-tax denominator."""
    return 6 * n_params


def consolidation_cost(method, n_anchored, sigma):
    """Extra ops the CONSOLIDATION step adds per optimiser step (beyond the shared
    forward/backward), on a digital accelerator."""
    c = StepCost()
    if method == "none":
        if sigma > 0:
            c.rng += n_anchored; c.adds += n_anchored
        return c
    if method in ("ou", "ewc"):
        c.adds += 2 * n_anchored                       # drift compute + apply
        if sigma > 0:
            c.rng += n_anchored; c.adds += n_anchored
    elif method == "mesu":
        c.adds += 3 * n_anchored                       # variance-scaled drift
        if sigma > 0:
            c.rng += n_anchored; c.adds += n_anchored
    elif method == "doob":
        c.adds += 2 * n_anchored                       # anchored drift
        c.tanh += n_anchored                           # tan() score
        c.adds += 2 * n_anchored                       # score scale + apply
        if sigma > 0:
            c.rng += n_anchored; c.adds += n_anchored
    return c


def step_energy_pj(method, n_params, sigma, *, substrate="gpu"):
    """Total per-step energy on a given substrate.
      gpu    : digital; forward/backward + consolidation ops all cost energy,
               INCLUDING the RNG that fabricates the noise.
      bss2   : analog; the synaptic MACs run at analog energy AND the intrinsic
               noise is free (no RNG, no scaled-add for the diffusion term). The
               Doob score is the only digital overhead (computed by the on-chip
               plasticity processor)."""
    fb = forward_backward_macs(n_params)
    con = consolidation_cost(method, n_params, sigma)
    if substrate == "gpu":
        return StepCost(macs=fb).energy_pj() + con.energy_pj()
    if substrate == "bss2":
        # analog MACs; intrinsic noise free -> drop the RNG and its scaled-add
        con_free = StepCost(adds=con.adds - (con.rng if sigma > 0 else 0),
                            tanh=con.tanh, rng=0)
        return StepCost(macs=fb).energy_pj(mac_pj=E_MAC_BSS2_PJ) + con_free.energy_pj()
    raise ValueError(substrate)


def noise_tax_ratio(method, n_params, sigma):
    """The fraction of a GPU consolidation step's energy that is SPENT
    fabricating + steering the noise a noisy chip would provide for free. This is
    the 'dividend a GPU has to pay to fake' the mechanism."""
    total = step_energy_pj(method, n_params, sigma, substrate="gpu")
    noiseless = step_energy_pj(method, n_params, 0.0, substrate="gpu")
    return (total - noiseless) / total if total > 0 else 0.0
