"""Regenerate paper/numbers.tex from committed results JSON. Never hand-type a
stat: the paper cites only \\N... macros emitted here. verify_regen.py byte-checks.

Run: python paper/gen_numbers.py   (re-run after any result changes)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"
SHORT = {"microsoft/Phi-3.5-mini-instruct": "Phi",
         "Qwen/Qwen2.5-7B-Instruct": "Qwen",
         "nvidia/Llama-3.1-Nemotron-Nano-8B-v1": "Nemo"}

macros = {}


def add(name, val):
    macros[name] = val


def load(name):
    p = RES / name
    return json.loads(p.read_text()) if p.exists() else None


def f2(x):
    return f"{x:+.2f}" if x < 0 else f"{x:.2f}"


# --- dataset + E0 ---
e0 = load("e0_results.json")
if e0:
    add("datasetStems", e0["meta"]["n_stems"])
    add("datasetItems", e0["meta"]["n_items"])
    for jid, s in SHORT.items():
        if jid in e0["per_judge"]:
            f = e0["per_judge"][jid]
            add(f"EzeroBetaS{s}", f2(f["beta_S"]))
            add(f"EzeroBetaG{s}", f2(f["beta_G"]))
            add(f"EzeroRatio{s}", f"{f['ratio_S_over_G']:.2f}")
            add(f"EzeroHack{s}", f"{e0['hackability'][jid]['hackability_index']:.2f}")
    add("EzeroPooledBetaS", f2(e0["pooled"]["beta_S"]))
    add("EzeroPooledBetaG", f2(e0["pooled"]["beta_G"]))
    add("EzeroPooledRatio", f"{e0['pooled']['ratio_S_over_G']:.2f}")
    add("EzeroPooledHack", f"{e0['pooled_hackability']['hackability_index']:.2f}")

# --- E1 length ---
e1l = load("e1_length_control.json")
if e1l:
    for jid, s in SHORT.items():
        if jid in e1l:
            v = e1l[jid]
            add(f"EoneLenBetaGbase{s}", f2(v["beta_G_nolen"]))
            add(f"EoneLenBetaGctrl{s}", f2(v["beta_G_withlen"]))
            add(f"EoneLenShrink{s}", f"{100*v['shrink_frac']:.0f}")

# --- E1 pairwise ---
e1p = load("e1_pairwise.json")
if e1p:
    for jid, s in SHORT.items():
        if jid in e1p["per_judge"]:
            v = e1p["per_judge"][jid]
            add(f"EonePair{s}", f"{v['P_pick_signaled_mean']:.2f}")
            add(f"EonePairLo{s}", f"{v['ci'][0]:.2f}")
            add(f"EonePairHi{s}", f"{v['ci'][1]:.2f}")

# --- E3 probe ---
e3 = load("e3_probe.json")
if e3:
    for jid, s in SHORT.items():
        if jid in e3["per_judge"]:
            r = e3["per_judge"][jid]
            add(f"EthreeBestLayer{s}", r["best_layer"])
            add(f"EthreeAuroc{s}", f"{r['best_auroc_in']:.3f}")
            oods = [min(v["auroc_ood_ml2econ"], v["auroc_ood_econ2ml"])
                    for v in r["per_layer"].values()
                    if v["auroc_ood_ml2econ"] == v["auroc_ood_ml2econ"]]
            add(f"EthreeOodMin{s}", f"{min(oods):.3f}")

# --- E4 multilayer (the fix fails) ---
e4 = load("e4_multilayer.json")
if e4:
    for jid, s in SHORT.items():
        if jid in e4["per_judge"]:
            sw = e4["per_judge"][jid]["sweep"]
            add(f"EfourBetaGbase{s}", f2(sw["0.0"]["beta_G"]))
            add(f"EfourBetaGabl{s}", f2(sw["1.0"]["beta_G"]))
            add(f"EfourBetaSbase{s}", f2(sw["0.0"]["beta_S"]))
            add(f"EfourBetaSabl{s}", f2(sw["1.0"]["beta_S"]))

# --- E5 reconciliation ---
e5 = load("e5_reconciliation.json")
if e5:
    for jid, s in SHORT.items():
        if jid in e5["per_judge"]:
            v = e5["per_judge"][jid]
            add(f"EfiveVarG{s}", f"{v['var_share_G']:.2f}")
            add(f"EfiveVarS{s}", f"{v['var_share_S']:.2f}")
            add(f"EfiveOver{s}", f"{v['over_rating_rate']:.2f}")
            add(f"EfiveUnder{s}", f"{v['under_rating_rate']:.2f}")
    add("EfivePooledVarG", f"{e5['pooled']['var_share_G']:.2f}")
    add("EfivePooledVarS", f"{e5['pooled']['var_share_S']:.2f}")

# --- E2 reward hack (may be absent while running) ---
e2 = load("e2_rewardhack.json")
if e2:
    for jid, s in SHORT.items():
        if jid in e2["per_judge"]:
            v = e2["per_judge"][jid]
            add(f"EtwoGain{s}", f2(v["gamed_gain_by_cell"]["LL"]))
            add(f"EtwoLLexceeds{s}", f"{100*v['ll_farmed_exceeds_hl_mean']:.0f}")
            add(f"EtwoLLbase{s}", f"{100*v['ll_baseline_exceeds_hl_mean']:.0f}")

lines = [f"% AUTO-GENERATED by paper/gen_numbers.py — do not edit by hand.",
         f"% {len(macros)} macros."]
for k in sorted(macros):
    lines.append(f"\\newcommand{{\\{k}}}{{{macros[k]}}}")
out = "\n".join(lines) + "\n"
(ROOT / "paper" / "numbers.tex").write_text(out, encoding="utf-8")
print(f"wrote paper/numbers.tex with {len(macros)} macros "
      f"(E2 {'included' if e2 else 'PENDING'})")
